# Generated by Django 5.2.4 on 2025-07-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='currency',
            field=models.CharField(default='₽', max_length=5),
        ),
    ]
